# Generated by Django 5.0 on 2024-01-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='susbscribed',
            new_name='subscribed',
        ),
    ]
